### ISSUE TITLE
卖出了之前不存在的标的

### ISSUE THREAD

**Issue by zqcccc** [bmpi-dev/invest-alchemy#4]
在 tg 中，2022年11月1日的操作中，卖出了 证券 etf ，但是好像之前就没有持仓，这是要把这个标的加入可选池子中的意思吗？

**Comment by madawei2699** [comment]
> 在 tg 中，2022年11月1日的操作中，卖出了 证券 etf ，但是好像之前就没有持仓，这是要把这个标的加入可选池子中的意思吗？

这是11和22均线价格相同导致的误报，这个bug一直没来得及解决。

**Comment by madawei2699** [comment]
Duplicate of #1
