### ISSUE TITLE
2023-02-03 可买ETF并未进入持仓列表

### ISSUE THREAD

**Issue by jacob2826** [bmpi-dev/invest-alchemy#5]
2023-02-02 tg上报信号
==Other ETF==
可买标的:
地产ETF(512200.SH)可买, 收盘价0.742, 11日均线0.736, 22日均线0.735

但该ETF 并未出现在2023-02-03的持仓中

**Comment by madawei2699** [comment]
这是个bug，长短均线价格一样时就会导致etf在那一天被消失了

**Comment by madawei2699** [comment]
Duplicate of #1
